import type { SuggestionBlock } from './types';

// Demo data for initial suggestions
export const DEMO_SUGGESTIONS: SuggestionBlock[] = [
  {
    id: 'cv-name-demo',
    blockId: 'cv-name',
    suggestions: [
      {
        id: 'suggestion-1',
        text: 'Consider using a professional title or subtitle below your name',
        startOffset: 0,
        endOffset: 5,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'work-position-demo',
    blockId: 'we-position-68e18a6a76a62e7302d55681',
    suggestions: [
      {
        id: 'suggestion-2',
        text: 'Make the job title more specific and descriptive',
        startOffset: 0,
        endOffset: 15,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-3',
        text: 'Consider adding the department or team name',
        startOffset: 20,
        endOffset: 35,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'work-name-demo',
    blockId: 'we-name-68e18a6a76a62e7302d55681',
    suggestions: [
      {
        id: 'suggestion-4',
        text: 'Include the company size or industry for context',
        startOffset: 0,
        endOffset: 20,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-5',
        text: 'Add a brief description of what the company does',
        startOffset: 25,
        endOffset: 40,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'job-type-demo',
    blockId: 'job-type-68e18a6a76a62e7302d55681',
    suggestions: [
      {
        id: 'suggestion-6',
        text: 'Specify if it was full-time, part-time, contract, or internship',
        startOffset: 0,
        endOffset: 25,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-7',
        text: 'Add remote/hybrid/on-site work arrangement if relevant',
        startOffset: 30,
        endOffset: 50,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'work-description-demo',
    blockId: '68e18a6a76a62e7302d55681',
    suggestions: [
      {
        id: 'suggestion-8',
        text: 'Start with strong action verbs like "Led", "Developed", "Implemented"',
        startOffset: 0,
        endOffset: 20,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-9',
        text: 'Quantify your impact: "Increased sales by 25%" or "Managed team of 8"',
        startOffset: 25,
        endOffset: 45,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-10',
        text: 'Use specific technologies and tools you worked with',
        startOffset: 50,
        endOffset: 70,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-11',
        text: 'Focus on results and outcomes rather than just duties',
        startOffset: 75,
        endOffset: 95,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-12',
        text: 'Include metrics: "Reduced costs by 15%" or "Improved efficiency by 30%"',
        startOffset: 100,
        endOffset: 120,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'education-demo-1',
    blockId: 'description-education-1',
    suggestions: [
      {
        id: 'suggestion-13',
        text: 'Add specific achievements like "Graduated Magna Cum Laude" or "GPA: 3.8/4.0"',
        startOffset: 0,
        endOffset: 15,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-14',
        text: 'Mention relevant coursework or capstone projects',
        startOffset: 20,
        endOffset: 35,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-15',
        text: "Include any academic honors, scholarships, or dean's list mentions",
        startOffset: 40,
        endOffset: 55,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'projects-demo-1',
    blockId: 'description-project-1',
    suggestions: [
      {
        id: 'suggestion-16',
        text: 'Add a brief description of the problem you solved',
        startOffset: 0,
        endOffset: 20,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-17',
        text: 'Include the tech stack and tools used',
        startOffset: 25,
        endOffset: 40,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-18',
        text: 'Mention the impact or results achieved',
        startOffset: 45,
        endOffset: 60,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'skills-demo-1',
    blockId: 'skills-list-1',
    suggestions: [
      {
        id: 'suggestion-19',
        text: 'Group related skills: "Programming: JavaScript, Python, Java"',
        startOffset: 0,
        endOffset: 25,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-20',
        text: 'Add proficiency levels: "Advanced", "Intermediate", "Beginner"',
        startOffset: 30,
        endOffset: 50,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'about-me-demo',
    blockId: 'about-me-description',
    suggestions: [
      {
        id: 'suggestion-21',
        text: 'Make it more specific and personal rather than generic',
        startOffset: 0,
        endOffset: 20,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-22',
        text: 'Include your career goals and what you bring to the table',
        startOffset: 25,
        endOffset: 45,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
      {
        id: 'suggestion-23',
        text: 'Keep it concise - 2-3 sentences maximum',
        startOffset: 50,
        endOffset: 65,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
  {
    id: 'contact-demo',
    blockId: 'contact-email-1',
    suggestions: [
      {
        id: 'suggestion-24',
        text: 'Use a professional email address if possible',
        startOffset: 0,
        endOffset: 15,
        createdAt: new Date(),
        authorName: 'AI Assistant',
        status: 'open',
      },
    ],
  },
];
